on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main
  
jobs:
  test-example-job:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: npm run test